### ISSUE TITLE
Need pure protobuf version first (gRPC later?)

### ISSUE THREAD

**Issue by ariddell** [sakrejda/servestan#1]
What's the short term goal here? Is it to have a working version of `stanc` (the executable that is part of cmdstan) which uses protocol buffers? If so, I think gRPC is overkill. (or are you just using gRPC to spec out the function signatures?)

You might find it useful to look at how RStan/PyStan compile model code. It's the function `stanc` in stanc.hpp (similar in RStan): https://github.com/stan-dev/pystan/blob/develop/pystan/stanc.hpp#L27

Suppose `stan::lang::compile` took protobuf messages as arguments and returned a protobuf message. All of `stanc.hpp` could be removed, which would be great. The story is roughly similar with CmdStan as well.

(Longer-term I think something with gRPC will be great.)

**Comment by sakrejda** [comment]
On Sat, Dec 5, 2015 at 3:57 PM, Allen Riddell notifications@github.com
wrote:

> What's the short term goal here? Is it to have a working version of stanc
> (the executable that is part of cmdstan) which uses protocol buffers? If
> so, I think gRPC is overkill. (or are you just using gRPC to spec out the
> function signatures?)
> 
> Short term: a stanc service in gRPC so you could send it stan code and get
> back c++ code regardless of which client you're working from.  Short term
> looks like it will be next week for a working prototype... so maybe
> overkill but if the framework does what it says it shouldn't get in the way.
> 
> You might find it useful to look at how RStan/PyStan compile model code.
> It's the function stanc in stanc.hpp (similar in RStan):
> https://github.com/stan-dev/pystan/blob/develop/pystan/stanc.hpp#L27
> 
> As an aside---where do you compile the c++ generated here to an
> executable?  I can't find it...
> 
> Suppose stan::lang::compile took protobuf messages as arguments and
> returned a protobuf message. All of stanc.hpp could be removed, which
> would be great. The story is roughly similar with CmdStan as well.
> 
> I'm starting to catch on to the vision here.  Looks like it's a pain in
> pystan (and really in rstan too) to marshall native variables into a format
> that can go into a c++ API.  I could do version of stan::lang::compile that
> takes protobuf messages pretty quickly (after this toy gRPC thing) but we
> can't just bring protobuf into Stan---that's a lot of maintenance
> complexity.  How about

1) A repo (say stan-dev/proto) for .proto files
2) This servestan repo for the gRPC client-server stanc version, relying on
stan-dev/proto
3) A separate repo that just does the shim over stanc, maybe a protobuf
writer callback for samples

If we do that I think in a couple of weeks we'll be in a place to figure
out what works and what doesn't.

**Comment by sakrejda** [comment]
I think this discussion is still better off on stan-dev for now, though
we're close to getting into the weeds.

**Comment by ariddell** [comment]
In that case, gRPC sounds fine and your plan is a good one.

I think 1) and 2) make sense. I think 3) could go inside stan-dev/proto for now, but this is up to you.

(personally, I think what stan-dev needs is a minimal working example.)

**Comment by ariddell** [comment]
re: the compilation, that's part of the mess that isn't duplicated in R and Python; it's R/Python specific. For Python you can look inside pystan/model.py to see how it gets done. The process is similar in R in general terms (but the code is completely different).
